In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## HW5-1

In [2]:
def leap (x):
    if 4< x <100:
        if x%4==0:
            print('西元 {}年是閏年'.format(x))
        else :
            print('西元 {}年是平年'.format(x))
    elif 100<x<400:
        if x%4==0 and x%100!=0:
            print('{}年是閏年'.format(x))
        else :
            print('西元 {}年是平年'.format(x))
    elif 400<x :
        if x%4==0 and x%100!=0 or x%400==0 :
               print('西元 {}年是閏年'.format(x))
        else :
               print('西元 {}年是平年'.format(x))
    elif x<=0:
        if (x-1)%4==0:
            x=abs(x)
            print('西元前 {}年是閏年'.format(x))
        elif x==0 :
            print('沒有西元0年')
        else :
            x=abs(x)
            print('西元前 {}年是平年'.format(x))
    else:
         print('西元 {}年是平年'.format(x))

In [3]:
leap(-3)

西元前 3年是閏年


## HW5-2

* 有疑惑應該是直接加就好 為何還需要寫函式

In [4]:
m1=np.random.randn(5,5)
m2=np.random.randn(5,5)

In [5]:
def matrix_plus (m1,m2):
    x=m1+m2
    print(x)

In [6]:
matrix_plus (m1,m2)

[[-1.85853541 -1.01660639  0.38216984  0.52388746  2.81541374]
 [ 2.05789202 -0.79035479  0.0807451  -1.39764132 -1.36532649]
 [-1.74336556 -0.63174836  1.30559997 -0.96293304  1.98409293]
 [-0.14086735 -0.6173618  -2.03468818  1.60316014  1.89039358]
 [-0.29856406  0.7189493  -0.56291084 -2.11162886 -1.07334003]]


## HW5-3

In [60]:
x=[[2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
[1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
[1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
[1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
[1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
[1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
[1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
[1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
[1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]]

index=['土語系','財政系','金融系','國貿系',
       '會計系','法律系','公行系','應數系','教育系']
columns=['國文','英文','數甲','數乙','物理',
                 '化學', '生物', '歷史','地理','公民']
grades=np.array([86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6])

In [61]:
df2 = pd.DataFrame(x , 
                   index=index,
                   columns=columns)

In [62]:
A = []
for i in range (9):
    x=df2.iloc[i]*grades
    x=sum(x)
    A.append(x)

In [63]:
A

[589.2,
 350.35,
 398.6,
 481.55,
 642.4499999999999,
 508.9,
 436.975,
 461.30000000000007,
 570.075]

In [64]:
df2['加權分'] =A

In [65]:
df2

國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民      加權分
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075

In [66]:
print(df2.iat[0,10])

589.2


## HW5-4

In [90]:
B=np.random.randn(8)
n=len(B)

In [91]:
for i in range(0,7):
    if B[i]>B[i+1]:
        temp=B[i]
        B[i]=B[i+1]
        B[i+1]=temp
    for j in range(1,8):
        if B[n-j]<B[n-j-1]:
            tem=B[n-j]
            B[n-j]=B[n-j-1]
            B[n-j-1]=tem

In [92]:
B

array([-1.36774583, -0.550262  , -0.22156324,  0.11720575,  0.84769882,
        0.84902897,  1.09207734,  1.22815854])

## 本來想嘗試表格 但不知道為什麼換起來很奇怪ＱＱ

In [72]:
df=df2
n=9
for i in range(0,8):
    if df.iat[i,10]>df.iat[i+1,10]:
        temp=df.iloc[i]
        df.iloc[i]=df.iloc[i+1]
        df.iloc[i+1]=temp
    for j in range(1,9):
        if df.iat[n-j,10]<df.iat[n-j-1,10]:
            tem=df.iloc[n-j]
            df.iloc[n-j]=df.iloc[n-j-1]
            df.iloc[n-j-1]=tem



In [73]:
df

國文   英文   數甲   數乙   物理   化學   生物   歷史   地理   公民     加權分
土語系  1.0  1.5  0.0  1.5  0.0  0.0  0.0  0.0  0.0  0.0  350.35
財政系  2.0  2.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  589.20
金融系  2.0  2.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  589.20
國貿系  2.0  2.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  589.20
會計系  1.5  2.0  0.0  2.0  0.0  0.0  0.0  1.0  1.0  0.0  642.45
法律系  1.5  2.0  0.0  2.0  0.0  0.0  0.0  1.0  1.0  0.0  642.45
公行系  1.5  2.0  0.0  2.0  0.0  0.0  0.0  1.0  1.0  0.0  642.45
應數系  1.5  2.0  0.0  2.0  0.0  0.0  0.0  1.0  1.0  0.0  642.45
教育系  1.5  2.0  0.0  2.0  0.0  0.0  0.0  1.0  1.0  0.0  642.45